---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
  labels:
    app: vault
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8200
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8200
  selector:
    app: vault

