apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: ExternalName
  externalName: react-service.staging.svc.cluster.local
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react

