apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: react
        tier: frontend
    spec:
      shareProcessNamespace: true

      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: secrets
        emptyDir: {}
      - name: react-config
        configMap:
          name: react-configmap
          defaultMode: 0777

      securityContext:
        fsGroup: 2000

      initContainers:
      # The vault-authenticator container authenticates the container using the
      # kubernetes auth method and puts the resulting token on the filesystem.
      - name: vault-authenticator
        image: sethvargo/vault-kubernetes-authenticator:0.2.0
        imagePullPolicy: IfNotPresent

        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/vaultproject.io

        env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-addr
              key: value
        - name: VAULT_K8S_MOUNT_PATH
          value: k8s
        - name: VAULT_ROLE
          value: ops
        - name: VAULT_CACERT
          value: /vault/tls/tls.crt

        securityContext:
          allowPrivilegeEscalation: false

      - name: consul-template
        image: hashicorp/consul-template:0.20.0-light
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add: ['SYS_PTRACE']
        args:
        - "-once"

        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: vault-token
          mountPath: /var/run/secrets/vaultproject.io
        - name: react-config
          mountPath: /etc/react-config

        env:
        - name: VAULT_ADDR
          valueFrom:
            secretKeyRef:
              name: vault-addr
              key: value
        - name: VAULT_CACERT
          value: /vault/tls/tls.crt

      containers:
      - name: react
        image: {{ IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: REACT_ENTRYPOINT
            value: /etc/react-config/entrypoint.sh
          - name: ENV_DIR
            value: /etc/secrets/config
          - name: OVERLAY
            value: {{ OVERLAY }}
        command: ["/bin/sh"]
        args: ["-c", "$(REACT_ENTRYPOINT) $(ENV_DIR) $(OVERLAY)"]
        resources:
          requests:
            memory: "1024Mi"
            cpu: "40m"
          limits:
            memory: "1024Mi"
            cpu: "40m"
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: react-config
          mountPath: /etc/react-config
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 130
          timeoutSeconds: 10
          failureThreshold: 10
