#
### SERVE
#
FROM nginx:alpine as serve

RUN apk update && apk upgrade && apk add py-pip && \
  apk add jq && \
  pip install yq

COPY mp-build/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY mp-build/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
