commonLabels:
  app: api

resources:
- deployment.yaml
- service.yaml
- hpa.yaml

configMapGenerator:
- name: api-configmap
  files:
  - env.yaml
  - api-env-to-json.sh
  - api-entrypoint.sh

generatorOptions:
  disableNameSuffixHash: true
