apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-deployment-restart
  namespace: production
subjects:
  - kind: ServiceAccount
    name: vault-deployment-restart
    namespace: production
