apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-deployment-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-deployment-restart
subjects:
  - kind: ServiceAccount
    name: vault-deployment-restart

