apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: vault-tls-certificate
  namespace: production
spec:
  issuerRef:
    name: production-clusterissuer
    kind: ClusterIssuer
  secretName: vault-prod-tls-certificate
  dnsNames:
  - "vault.example.com"
  acme:
    config:
    - dns01:
        provider: cloudflare
      domains:
      - "vault.example.com"
