commonLabels:
  environment: dev
commonAnnotations:
  note: Dev react
  pr-number: "{{ PR_NUMBER }}"
bases:
- ../staging

patches:
- path: deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: react
- path: hpa.yaml
  target:
    group: autoscaling
    version: v2beta2
    kind: HorizontalPodAutoscaler

configMapGenerator:
- name: react-configmap
  behavior: merge
  files:
  - dev.yaml
