version: '3'
services:
  nginx:
    build:
      context: .
    container_name: local_nginx
    volumes:
      - ./docker-entrypoint.sh:/tmp/docker-entrypoint.sh
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    entrypoint:
      - bash
      - /tmp/docker-entrypoint.sh
    command: ['nginx', '-g', 'daemon off;']
